# Generated by Django 5.2.9 on 2025-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='user',
        ),
        migrations.AddField(
            model_name='technician',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='idproof',
            field=models.FileField(default='', upload_to='idproofs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technician',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='skill',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technician',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
