# Generated by Django 5.2.9 on 2025-12-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0003_remove_technician_is_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='password',
        ),
        migrations.AddField(
            model_name='technician',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technician',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='technician',
            name='skill',
            field=models.CharField(choices=[('AC Repair', 'AC Repair'), ('Refrigerator Repair', 'Refrigerator Repair'), ('Washing Machine Repair', 'Washing Machine Repair'), ('Microwave Repair', 'Microwave Repair'), ('Television Repair', 'Television Repair'), ('Plumbing', 'Plumbing'), ('Electrical Work', 'Electrical Work')], max_length=100),
        ),
    ]
