# Generated by Django 5.2.9 on 2025-12-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0010_servicerequest_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
