# Generated by Django 5.2.9 on 2025-12-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0011_servicerequest_rating_servicerequest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technician',
            name='discount_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_obj', to='homeservice.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservice.technician')),
            ],
        ),
    ]
