# Generated by Django 5.2.9 on 2026-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0013_technicianpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='technician',
            name='skill',
            field=models.CharField(choices=[('AC Repair', 'AC Repair'), ('Refrigerator Repair', 'Refrigerator Repair'), ('Washing Machine Repair', 'Washing Machine Repair'), ('Microwave Repair', 'Microwave Repair'), ('Television Repair', 'Television Repair'), ('Plumbing', 'Plumbing'), ('Electrical Work', 'Electrical Work'), ('Others', 'Others')], max_length=100),
        ),
    ]
