# Generated by Django 5.2.9 on 2026-01-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0014_servicerequest_location_alter_technician_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='location',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='technician',
            name='address',
            field=models.CharField(blank=True, help_text="Technician's home address", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='service_area',
            field=models.JSONField(default=list, help_text="List of nearby locations the technician can service (e.g., ['Aluva', 'Kochi', 'Perumbavoor'])"),
        ),
    ]
