# Generated by Django 5.2.9 on 2026-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0015_remove_technician_location_technician_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='address',
            field=models.CharField(help_text="Technician's home address", max_length=200),
        ),
    ]
