# Generated by Django 5.2.9 on 2026-01-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0016_auto_20260110_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='service_area',
        ),
        migrations.AddField(
            model_name='technician',
            name='service_locations',
            field=models.TextField(blank=True, help_text='Comma separated areas where technician can work', null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='address',
            field=models.TextField(help_text="Technician's home address"),
        ),
    ]
