# Generated by Django 5.2.9 on 2026-01-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0017_remove_technician_service_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='service_locations',
            field=models.TextField(help_text='Comma separated areas where technician can work'),
        ),
    ]
