# Generated by ChatGPT - add technician photo field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0022_fix_missing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='technicians/photos/'),
        ),
    ]
