# Generated by ChatGPT - add technician experience_certificate field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0023_technician_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='experience_certificates/'),
        ),
    ]
