# Generated by Django 6.0.1 on 2026-01-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0024_add_experience_certificate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicerequest',
            name='completed_requires_technician',
        ),
    ]
