# Generated by Django 6.0.1 on 2026-01-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0025_remove_servicerequest_completed_requires_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='admin_notified',
            field=models.BooleanField(default=False, help_text='Set True when admin has been shown a one-time notification for this signup'),
        ),
    ]
