# Generated by Django on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0026_technician_admin_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianpayment',
            name='admin_notified',
            field=models.BooleanField(default=False, help_text='Set True when admin has been shown a one-time notification for this payment'),
        ),
    ]
