# Generated by Django 6.0.1 on 2026-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0027_payment_admin_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open for Technicians'), ('assigned', 'Assigned'), ('rescheduled', 'Rescheduled'), ('accepted', 'Accepted by User'), ('reschedule_rejected', 'Reschedule Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
