# Generated by Django 6.0.1 on 2026-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0028_servicerequest_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='suggested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
